services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app_network

  backend:
    build:
      context: ./backend/services/api
    command: python run.py
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/data
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_network
    restart: on-failure

  celery_worker_fast:
    build:
      context: ./backend/services/worker_fast
    volumes:
      - backend_data:/app/data
    env_file:
      - .env
    depends_on:
      - redis
      - backend
    networks:
      - app_network
    restart: on-failure

  celery_worker_heavy:
    build:
      context: ./backend/services/worker_heavy
    shm_size: '2gb'
    stop_grace_period: 60s
    volumes:
      - backend_data:/app/data
    env_file:
      - .env
    depends_on:
      - redis
      - backend
    networks:
      - app_network
    restart: on-failure

  celery_worker_chat:
    build:
      context: ./backend/services/worker_chat
    volumes:
      - backend_data:/app/data
    env_file:
      - .env
    depends_on:
      - redis
      - backend
    networks:
      - app_network
    restart: on-failure

  celery_beat:
    build:
      context: ./backend/services/beat
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_network
    restart: on-failure

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  backend_data:
